import { PhysicalLibrary } from "@/types";

/**
 * 동작구 도서관 마스터 데이터
 * 도서관명은 lib.dongjak.go.kr HTML 소스의 실제 표기 기준
 */
export const DONGJAK_LIBRARIES: Omit<
  PhysicalLibrary,
  "available" | "callNumber" | "returnDueDate" | "distance" | "searchResultUrl"
>[] = [
  // ─── 구립도서관 ────────────────────────────────────────────
  {
    id: "lib_MK",
    libraryName: "김영삼도서관",
    libraryType: "library",
    address: "서울특별시 동작구 매봉로 1",
    latitude: 37.4967,
    longitude: 126.9508,
    tel: "02-827-0557",
    openingHours: "평일 09:00~22:00 / 주말 09:00~17:00 / 월요일·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_ML",
    libraryName: "까망돌도서관",
    libraryType: "library",
    address: "서울특별시 동작구 보라매로5길 15",
    latitude: 37.4923,
    longitude: 126.9255,
    tel: "02-820-9256",
    openingHours: "평일 09:00~22:00 / 주말 09:00~17:00 / 월요일·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_MA",
    libraryName: "사당솔밭도서관",
    libraryType: "library",
    address: "서울특별시 동작구 동작대로29길 63-26",
    latitude: 37.4771,
    longitude: 126.9826,
    tel: "02-533-6750",
    openingHours: "평일 09:00~22:00 / 주말 09:00~17:00 / 월요일·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_MN",
    libraryName: "신대방 누리도서관",
    libraryType: "library",
    address: "서울특별시 동작구 신대방2동",
    latitude: 37.4948,
    longitude: 126.9196,
    tel: "02-820-9560",
    openingHours: "평일 09:00~22:00 / 주말 09:00~17:00 / 월요일·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_MC",
    libraryName: "동작영어마루도서관",
    libraryType: "library",
    address: "서울특별시 동작구 현충로 지하",
    latitude: 37.5044,
    longitude: 126.9625,
    tel: "02-815-0557",
    openingHours: "평일 09:00~22:00 / 주말 09:00~17:00 / 월요일·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_MF",
    libraryName: "약수도서관",
    libraryType: "library",
    address: "서울특별시 동작구 양녕로 지하",
    latitude: 37.5131,
    longitude: 126.9427,
    tel: "02-823-0557",
    openingHours: "평일 09:00~22:00 / 주말 09:00~17:00 / 월요일·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_ME",
    libraryName: "동작샘터도서관",
    libraryType: "library",
    address: "서울특별시 동작구 동작대로 지하",
    latitude: 37.5005,
    longitude: 126.9484,
    tel: "02-599-0557",
    openingHours: "평일 09:00~22:00 / 주말 09:00~17:00 / 월요일·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_MD",
    libraryName: "대방어린이도서관",
    libraryType: "library",
    address: "서울특별시 동작구 여의대방로16길 61",
    latitude: 37.5119,
    longitude: 126.9256,
    tel: "02-820-9254",
    openingHours: "평일 09:00~18:00 / 주말 09:00~17:00 / 월요일·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  // ─── 작은도서관 ────────────────────────────────────────────
  {
    id: "lib_MH",
    libraryName: "다울작은도서관",
    libraryType: "small_library",
    address: "서울특별시 동작구 상도동",
    latitude: 37.5005,
    longitude: 126.9420,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_MJ",
    libraryName: "국사봉숲속작은도서관",
    libraryType: "small_library",
    address: "서울특별시 동작구 양녕로23길 27",
    latitude: 37.4988,
    longitude: 126.9464,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_MP",
    libraryName: "신대방햇살",
    libraryType: "small_library",
    address: "서울특별시 동작구 신대방동",
    latitude: 37.4935,
    longitude: 126.9210,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },

  // ─── 동 작은도서관 ────────────────────────────────────────
  {
    id: "lib_NA",
    libraryName: "노량진1동 작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 노량진1동",
    latitude: 37.5131,
    longitude: 126.9427,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_NB",
    libraryName: "노량진2동 작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 노량진2동",
    latitude: 37.5110,
    longitude: 126.9380,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_NH",
    libraryName: "사당1동 작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 사당1동",
    latitude: 37.4800,
    longitude: 126.9780,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_NJ",
    libraryName: "사당2동 작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 사당2동",
    latitude: 37.4820,
    longitude: 126.9800,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_NK",
    libraryName: "사당3동 작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 사당3동",
    latitude: 37.4840,
    longitude: 126.9820,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_NM",
    libraryName: "사당5동 작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 사당5동",
    latitude: 37.4860,
    longitude: 126.9840,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_NC",
    libraryName: "상도1동 작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 상도1동",
    latitude: 37.4990,
    longitude: 126.9440,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_ND",
    libraryName: "상도2동 작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 상도2동",
    latitude: 37.4970,
    longitude: 126.9460,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_NE",
    libraryName: "상도3동 작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 상도3동",
    latitude: 37.4950,
    longitude: 126.9480,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_NF",
    libraryName: "상도4동 작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 상도4동",
    latitude: 37.4930,
    longitude: 126.9500,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_NQ",
    libraryName: "신대방2동 작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 신대방2동",
    latitude: 37.4920,
    longitude: 126.9180,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_NG",
    libraryName: "흑석동 작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 흑석동",
    latitude: 37.5044,
    longitude: 126.9625,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_NN",
    libraryName: "대방동 작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 대방동",
    latitude: 37.5100,
    longitude: 126.9270,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  // ─── 사립 작은도서관 ────────────────────────────────────────
  {
    id: "lib_PG",
    libraryName: "담소작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 상도동",
    latitude: 37.4980,
    longitude: 126.9450,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_PE",
    libraryName: "상도중앙작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 상도동",
    latitude: 37.4960,
    longitude: 126.9470,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_PC",
    libraryName: "성대골 어린이도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 상도동",
    latitude: 37.4975,
    longitude: 126.9455,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_PH",
    libraryName: "아트&힐링작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 사당동",
    latitude: 37.4830,
    longitude: 126.9810,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_PF",
    libraryName: "지혜샘터작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 상도동",
    latitude: 37.4965,
    longitude: 126.9475,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_PB",
    libraryName: "행복한래미안작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 상도동",
    latitude: 37.4985,
    longitude: 126.9445,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_PJ",
    libraryName: "양문작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 신대방동",
    latitude: 37.4940,
    longitude: 126.9200,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
  {
    id: "lib_NR",
    libraryName: "만나작은도서관",
    libraryType: "small_library" as const,
    address: "서울특별시 동작구 신대방동",
    latitude: 37.4935,
    longitude: 126.9215,
    openingHours: "평일 10:00~18:00 / 주말·공휴일 휴관",
    homepageUrl: "https://lib.dongjak.go.kr",
  },
];

export function getLibraryById(id: string) {
  return DONGJAK_LIBRARIES.find((lib) => lib.id === id) ?? null;
}

export function getLibrariesByType(type: PhysicalLibrary["libraryType"]) {
  return DONGJAK_LIBRARIES.filter((lib) => lib.libraryType === type);
}
